# Generated by Django 3.2.16 on 2023-02-01 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('in_stock', models.BooleanField(default=False)),
                ('number_of_sold', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'букет',
                'verbose_name_plural': 'букеты',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
            options={
                'verbose_name': 'консультация',
                'verbose_name_plural': 'консультации',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACCEPTED', 'Принят'), ('PROCESSING', 'Обрабатывается'), ('BEING_DELIVERED', 'Доставляется'), ('CANCELLED', 'Отменен'), ('DELIVERED', 'Доставлен')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_time', models.CharField(choices=[('AS_SOON_AS_POSSIBLE', 'Как можно скорее'), ('FROM_10_TO_12', 'с 10:00 до 12:00'), ('FROM_12_TO_14', 'с 12:00 до 14:00'), ('FROM_14_TO_16', 'с 14:00 до 16:00'), ('FROM_16_TO_18', 'с 16:00 до 18:00'), ('FROM_18_TO_20', 'с 18:00 до 20:00')], max_length=19)),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bouquet_orders', to='order_bouquet.bouquet')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_orders', to='order_bouquet.client')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courier_orders', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.AddField(
            model_name='bouquet',
            name='category',
            field=models.ManyToManyField(related_name='bouquets', to='order_bouquet.Category'),
        ),
    ]
