# Generated by Django 3.2.16 on 2023-02-05 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order_bouquet', '0002_auto_20230201_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Ожидание'), ('COMPLETED', 'Проведена')], default='WAITING', max_length=9, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bouquet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bouquet_orders', to='order_bouquet.bouquet', verbose_name='Букет'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_orders', to='order_bouquet.client', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courier_orders', to=settings.AUTH_USER_MODEL, verbose_name='Курьер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(choices=[('AS_SOON_AS_POSSIBLE', 'Как можно скорее'), ('FROM_10_TO_12', 'с 10:00 до 12:00'), ('FROM_12_TO_14', 'с 12:00 до 14:00'), ('FROM_14_TO_16', 'с 14:00 до 16:00'), ('FROM_16_TO_18', 'с 16:00 до 18:00'), ('FROM_18_TO_20', 'с 18:00 до 20:00')], max_length=19, verbose_name='Время доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager_orders', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Принят'), ('PROCESSING', 'Обрабатывается'), ('BEING_DELIVERED', 'Доставляется'), ('CANCELLED', 'Отменен'), ('DELIVERED', 'Доставлен')], max_length=15, verbose_name='Статус'),
        ),
    ]
