# Generated by Django 3.2.16 on 2023-02-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_bouquet', '0002_auto_20230201_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='price',
            field=models.IntegerField(),
        ),
    ]
