# Generated by Django 3.2.16 on 2023-02-06 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order_bouquet', '0003_alter_bouquet_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bouquet',
            options={'verbose_name': 'Букет', 'verbose_name_plural': 'Букеты'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='consultation',
            options={'verbose_name': 'Консультация', 'verbose_name_plural': 'Консультации'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Ожидание'), ('COMPLETED', 'Проведена')], default='WAITING', max_length=9, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='category',
            field=models.ManyToManyField(related_name='bouquets', to='order_bouquet.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='image',
            field=models.ImageField(upload_to='images/catalog', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='in_stock',
            field=models.BooleanField(default=False, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='number_of_sold',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во проданных'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='structure',
            field=models.CharField(max_length=255, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bouquet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bouquet_orders', to='order_bouquet.bouquet', verbose_name='Букет'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_orders', to='order_bouquet.client', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courier_orders', to=settings.AUTH_USER_MODEL, verbose_name='Курьер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(choices=[('AS_SOON_AS_POSSIBLE', 'Как можно скорее'), ('FROM_10_TO_12', 'с 10:00 до 12:00'), ('FROM_12_TO_14', 'с 12:00 до 14:00'), ('FROM_14_TO_16', 'с 14:00 до 16:00'), ('FROM_16_TO_18', 'с 16:00 до 18:00'), ('FROM_18_TO_20', 'с 18:00 до 20:00')], max_length=19, verbose_name='Время доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager_orders', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NOT_PAID', 'Не оплачен'), ('ACCEPTED', 'Принят'), ('PROCESSING', 'Обрабатывается'), ('BEING_DELIVERED', 'Доставляется'), ('CANCELLED', 'Отменен'), ('DELIVERED', 'Доставлен')], max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
    ]
