# Generated by Django 3.2.16 on 2023-02-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_bouquet', '0003_alter_bouquet_price'),
        ('order_bouquet', '0003_auto_20230205_1607'),
    ]

    operations = [
    ]
